# Site settings
title: Harsha Lab
email: reach_hlab [at] protonmail.com
url: "http://hlab.in" 
twitter_username: harshkn
github_username:  harshkn
excerpt_separator: <!--summary-->
comments: true

# Build settings
markdown: kramdown
paginate: 5

gems:
- jekyll-lunr-js-search
- jekyll-paginate
- jekyll-mentions
- jekyll-gist

collections:
  teaching:
    output: true
